version: '3.3'

services:
    app:
      build: ./express_next
      container_name: node12
      ports:
        - "80:8081"
      env_file: .env
      restart: always
      links:
        - db
    db:
      build: ./mysql
      container_name: mysql8
      volumes:
        - db_data:/var/lib/mysql
      env_file: .env
      restart: always
      

# volumes を定義する
volumes:
  # volume の名前を指定
  db_data:
    # Compose の外ですでに作成済みの volume を指定する場合は true を設定する。
    # そうすると、 docker-compose up 時に Compose は volume を作成しようとしません。
    # かつ、指定した volume が存在しないとエラーを raise します。
    external: true

